# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  dev-app:
    container_name: time-track-dev
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
    command: npm run debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:3000
      - 9229:9229
    restart: unless-stopped
    links:
      - mongo
      - mongo-express
      - mail-catcher
  prod-app:
    container_name: time-track-prod
    build:
      context: .
      target: production
    environment:
      NODE_ENV: production
    env_file:
      - .env
    command: npm run prod
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./logs/:/usr/src/app/logs
    restart: unless-stopped
    links:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:8
    container_name: time-track-mongo
    ports:
      - ${DB_PORT}:27017
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - ${DATABASE_VOLUME_MOUNT}:/data/db
    restart: unless-stopped
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: time-track-mongo-express-ui
    ports:
      - ${MONGO_EXPRESS_UI_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
    restart: unless-stopped
    links:
      - mongo
    networks:
      - app-network

  mail-catcher:
    image: sj26/mailcatcher
    container_name: time-track-mailcatcher
    ports:
      - ${MAILCATCHER_PORT}:1080
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
